import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { playPremiumSound } from "@/lib/premiumSounds";
import { playSound } from "@/lib/sounds";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface Msg {
  role: "user" | "assistant";
  content: string;
  timestamp: number;
  imageUrl?: string; // attached image (user upload or generated)
  searchQueries?: string[]; // web search queries used
  sources?: { title: string; uri: string }[];
  isGenerated?: boolean; // image generated by bot
}

const CHAT_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/schooltrade-bot`;

const getChatKey = () => {
  try {
    const userCode = localStorage.getItem("userCode") || "default";
    return `schooltrade-bot-chat-${userCode}`;
  } catch { return "schooltrade-bot-chat-default"; }
};

const loadMessages = (): Msg[] => {
  try {
    const saved = localStorage.getItem(getChatKey());
    if (saved) return JSON.parse(saved);
  } catch { /* ignore */ }
  return [];
};

const saveMessages = (msgs: Msg[]) => {
  try { localStorage.setItem(getChatKey(), JSON.stringify(msgs)); } catch { /* ignore */ }
};

const fileToDataUrl = (file: File): Promise<string> => new Promise((res, rej) => {
  const reader = new FileReader();
  reader.onload = () => res(reader.result as string);
  reader.onerror = rej;
  reader.readAsDataURL(file);
});

const detectImageRequest = (text: string): string | null => {
  const t = text.trim();
  const patterns = [
    /^(?:צייר|תצייר|תייצר|ייצר|תיצור|צור|תכין|הכן)\s+(?:לי\s+)?(?:תמונה|תמונת)\s+(?:של\s+)?(.+)$/i,
    /^(?:generate|create|draw|make)\s+(?:an?\s+)?(?:image|picture|photo)\s+(?:of\s+)?(.+)$/i,
    /^תמונה של\s+(.+)$/i,
  ];
  for (const p of patterns) {
    const m = t.match(p);
    if (m) return m[1].trim();
  }
  return null;
};

export const SchooltradeBot = () => {
  const [messages, setMessages] = useState<Msg[]>(() => loadMessages());
  const [input, setInput] = useState("");
  const [pendingImage, setPendingImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [statusText, setStatusText] = useState<string>("");
  const [clearing, setClearing] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (messages.length > 0) saveMessages(messages);
  }, [messages]);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, statusText]);

  const clearChat = () => {
    playSound("click");
    setClearing(true);
    setTimeout(() => {
      localStorage.removeItem(getChatKey());
      setMessages([]);
      setClearing(false);
      playPremiumSound("sparkle");
    }, 400);
  };

  const handleFilePick = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    e.target.value = "";
    if (!f) return;
    if (!f.type.startsWith("image/")) return;
    if (f.size > 8 * 1024 * 1024) {
      alert("התמונה גדולה מדי (מקסימום 8MB)");
      return;
    }
    const dataUrl = await fileToDataUrl(f);
    setPendingImage(dataUrl);
    playSound("click");
  };

  const generateImage = async (prompt: string) => {
    setIsLoading(true);
    setStatusText("🎨 מייצר תמונה...");
    try {
      const resp = await fetch(CHAT_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ mode: "generate_image", prompt }),
      });
      const data = await resp.json();
      if (!resp.ok) {
        setMessages(prev => [...prev, {
          role: "assistant",
          content: data.error || "שגיאה ביצירת תמונה",
          timestamp: Date.now(),
        }]);
      } else {
        setMessages(prev => [...prev, {
          role: "assistant",
          content: data.text || `הנה התמונה שביקשת: "${prompt}"`,
          imageUrl: data.image,
          isGenerated: true,
          timestamp: Date.now(),
        }]);
        playPremiumSound("sparkle");
      }
    } catch (e) {
      console.error(e);
      setMessages(prev => [...prev, {
        role: "assistant",
        content: "שגיאה בחיבור לשרת",
        timestamp: Date.now(),
      }]);
    } finally {
      setIsLoading(false);
      setStatusText("");
    }
  };

  const send = async () => {
    const text = input.trim();
    if ((!text && !pendingImage) || isLoading) return;

    playSound("click");

    const userMsg: Msg = {
      role: "user",
      content: text,
      timestamp: Date.now(),
      ...(pendingImage ? { imageUrl: pendingImage } : {}),
    };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput("");
    const attachedImage = pendingImage;
    setPendingImage(null);

    // If pure image-generation request (no image uploaded), use generation endpoint
    if (!attachedImage) {
      const genPrompt = detectImageRequest(text);
      if (genPrompt) {
        await generateImage(genPrompt);
        return;
      }
    }

    setIsLoading(true);
    setStatusText(attachedImage ? "🖼️ מנתח את התמונה..." : "💭 חושב...");

    // Build API messages — include image as multimodal content if present
    const apiMessages = newMessages.map((m, idx) => {
      const isLast = idx === newMessages.length - 1;
      if (isLast && attachedImage) {
        return {
          role: m.role,
          content: [
            { type: "text", text: m.content || "תאר את התמונה הזו בעברית בצורה מפורטת." },
            { type: "image_url", image_url: { url: attachedImage } },
          ],
        };
      }
      // For older messages with images, drop the image (history simplification)
      return { role: m.role, content: m.content };
    });

    let assistantSoFar = "";
    let collectedQueries: string[] = [];
    let collectedSources: { title: string; uri: string }[] = [];
    let firstChunk = true;

    const upsertAssistant = (chunk: string) => {
      assistantSoFar += chunk;
      if (firstChunk) {
        firstChunk = false;
        setStatusText("");
      }
      setMessages(prev => {
        const last = prev[prev.length - 1];
        if (last?.role === "assistant" && !last.imageUrl) {
          return prev.map((m, i) => (i === prev.length - 1 ? { ...m, content: assistantSoFar, searchQueries: collectedQueries, sources: collectedSources } : m));
        }
        return [...prev, {
          role: "assistant",
          content: assistantSoFar,
          timestamp: Date.now(),
          searchQueries: collectedQueries,
          sources: collectedSources,
        }];
      });
    };

    const handleParsedDelta = (parsed: any) => {
      const delta = parsed.choices?.[0]?.delta;
      if (!delta) return;
      const content = delta.content as string | undefined;
      if (content) upsertAssistant(content);

      // Try to capture grounding metadata from various possible locations
      const grounding = parsed.choices?.[0]?.groundingMetadata
        || delta.groundingMetadata
        || parsed.groundingMetadata;
      if (grounding) {
        const queries = grounding.webSearchQueries || grounding.searchQueries;
        if (Array.isArray(queries) && queries.length) {
          collectedQueries = Array.from(new Set([...collectedQueries, ...queries]));
          if (firstChunk) setStatusText(`🔍 מחפש: ${queries[0]}`);
        }
        const chunks = grounding.groundingChunks || grounding.groundingSupports;
        if (Array.isArray(chunks)) {
          for (const c of chunks) {
            const w = c.web || c;
            if (w?.uri) {
              collectedSources.push({ title: w.title || w.uri, uri: w.uri });
            }
          }
          // dedupe
          const seen = new Set<string>();
          collectedSources = collectedSources.filter(s => {
            if (seen.has(s.uri)) return false;
            seen.add(s.uri);
            return true;
          });
        }
      }
    };

    try {
      const resp = await fetch(CHAT_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ messages: apiMessages }),
      });

      if (!resp.ok || !resp.body) {
        const err = await resp.json().catch(() => ({ error: "שגיאה" }));
        upsertAssistant(err.error || "שגיאה בתקשורת עם הבוט");
        setIsLoading(false);
        setStatusText("");
        return;
      }

      const reader = resp.body.getReader();
      const decoder = new TextDecoder();
      let textBuffer = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        textBuffer += decoder.decode(value, { stream: true });

        let newlineIndex: number;
        while ((newlineIndex = textBuffer.indexOf("\n")) !== -1) {
          let line = textBuffer.slice(0, newlineIndex);
          textBuffer = textBuffer.slice(newlineIndex + 1);
          if (line.endsWith("\r")) line = line.slice(0, -1);
          if (line.startsWith(":") || line.trim() === "") continue;
          if (!line.startsWith("data: ")) continue;
          const jsonStr = line.slice(6).trim();
          if (jsonStr === "[DONE]") break;
          try {
            const parsed = JSON.parse(jsonStr);
            handleParsedDelta(parsed);
          } catch {
            textBuffer = line + "\n" + textBuffer;
            break;
          }
        }
      }

      if (textBuffer.trim()) {
        for (let raw of textBuffer.split("\n")) {
          if (!raw) continue;
          if (raw.endsWith("\r")) raw = raw.slice(0, -1);
          if (raw.startsWith(":") || raw.trim() === "") continue;
          if (!raw.startsWith("data: ")) continue;
          const jsonStr = raw.slice(6).trim();
          if (jsonStr === "[DONE]") continue;
          try {
            const parsed = JSON.parse(jsonStr);
            handleParsedDelta(parsed);
          } catch { /* ignore */ }
        }
      }

      playPremiumSound("sparkle");
    } catch (e) {
      console.error(e);
      upsertAssistant("שגיאה בחיבור לשרת");
    } finally {
      setIsLoading(false);
      setStatusText("");
    }
  };

  return (
    <div className="space-y-4 max-w-2xl mx-auto" dir="rtl">
      <div className="text-center mb-4">
        <h3 className="text-2xl font-bold premium-text-glow text-[#00C853]">🤖 schooltrade bot (beta)</h3>
        <p className="text-sm text-muted-foreground">חיפוש באינטרנט · ניתוח תמונות · יצירת תמונות</p>
      </div>

      <Card className="border-[#00C853]/30 bg-card/80 backdrop-blur-sm overflow-hidden">
        <div ref={scrollRef} className={`h-[420px] overflow-y-auto p-4 space-y-3 transition-opacity duration-300 ${clearing ? "opacity-0" : "opacity-100"}`}>
          {messages.length === 0 && (
            <div className="text-center text-muted-foreground py-12 space-y-2">
              <div className="text-4xl">🤖</div>
              <p className="font-bold">שלום! אני schooltrade bot (beta)</p>
              <p className="text-sm">🔍 אני יכול לחפש מידע באינטרנט בזמן אמת</p>
              <p className="text-sm">🖼️ לנתח תמונות שתשלח לי</p>
              <p className="text-sm">🎨 ולייצר תמונות לפי בקשתך</p>
              <p className="text-xs mt-3 opacity-70">לדוגמה: "צייר לי תמונה של חתול בחלל"</p>
            </div>
          )}

          {messages.map((msg, i) => (
            <div key={i} className={`flex ${msg.role === "user" ? "justify-start" : "justify-end"}`}
              style={{ animation: "fadeSlideIn 0.3s ease-out" }}>
              <div className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
                msg.role === "user" ? "bg-primary/10 border border-primary/20" : "bg-[#00C853]/10 border border-[#00C853]/20"
              }`}>
                {msg.role === "assistant" && <span className="text-xs text-[#00C853] font-bold block mb-1">🤖 הבוט</span>}

                {msg.imageUrl && (
                  <div className="mb-2">
                    <img
                      src={msg.imageUrl}
                      alt={msg.isGenerated ? "תמונה שנוצרה" : "תמונה"}
                      className="rounded-lg max-w-full max-h-72 object-contain border border-border"
                      loading="lazy"
                    />
                    {msg.isGenerated && (
                      <a
                        href={msg.imageUrl}
                        download="schooltrade-bot-image.png"
                        className="inline-block mt-1 text-xs text-[#00C853] hover:underline"
                      >
                        ⬇️ הורד תמונה
                      </a>
                    )}
                  </div>
                )}

                {msg.content && (
                  <div className="prose prose-sm dark:prose-invert max-w-none break-words [&_p]:my-1 [&_ul]:my-1 [&_ol]:my-1 [&_a]:text-[#00C853]">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.content}</ReactMarkdown>
                  </div>
                )}

                {msg.searchQueries && msg.searchQueries.length > 0 && (
                  <div className="mt-2 pt-2 border-t border-[#00C853]/20">
                    <div className="text-[10px] font-bold text-[#00C853] mb-1">🔍 חיפושים שבוצעו:</div>
                    <div className="flex flex-wrap gap-1">
                      {msg.searchQueries.map((q, qi) => (
                        <span key={qi} className="text-[10px] bg-[#00C853]/15 px-2 py-0.5 rounded-full">{q}</span>
                      ))}
                    </div>
                  </div>
                )}

                {msg.sources && msg.sources.length > 0 && (
                  <div className="mt-2 pt-2 border-t border-[#00C853]/20">
                    <div className="text-[10px] font-bold text-[#00C853] mb-1">📚 מקורות:</div>
                    <ul className="space-y-0.5">
                      {msg.sources.slice(0, 5).map((s, si) => (
                        <li key={si} className="text-[10px]">
                          <a href={s.uri} target="_blank" rel="noopener noreferrer" className="text-[#00C853] hover:underline truncate block">
                            {si + 1}. {s.title}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="text-[10px] text-muted-foreground mt-1 opacity-60">
                  {new Date(msg.timestamp).toLocaleTimeString("he-IL", { hour: "2-digit", minute: "2-digit" })}
                </div>
              </div>
            </div>
          ))}

          {isLoading && (
            <div className="flex justify-end">
              <div className="bg-[#00C853]/10 border border-[#00C853]/20 rounded-2xl px-4 py-3 space-y-2">
                {statusText && (
                  <div className="text-xs text-[#00C853] font-medium animate-pulse">{statusText}</div>
                )}
                <div className="flex gap-1">
                  <span className="w-2 h-2 rounded-full bg-[#00C853] animate-bounce" style={{ animationDelay: "0ms" }} />
                  <span className="w-2 h-2 rounded-full bg-[#00C853] animate-bounce" style={{ animationDelay: "150ms" }} />
                  <span className="w-2 h-2 rounded-full bg-[#00C853] animate-bounce" style={{ animationDelay: "300ms" }} />
                </div>
              </div>
            </div>
          )}
        </div>

        {pendingImage && (
          <div className="border-t border-[#00C853]/20 p-2 flex items-center gap-2 bg-[#00C853]/5">
            <img src={pendingImage} alt="מצורפת" className="h-14 w-14 rounded-lg object-cover border border-[#00C853]/30" />
            <span className="text-xs text-muted-foreground flex-1">תמונה מצורפת — תישלח עם ההודעה הבאה</span>
            <Button size="sm" variant="ghost" onClick={() => setPendingImage(null)} className="text-xs">✕</Button>
          </div>
        )}

        <div className="border-t border-[#00C853]/20 p-3 flex gap-2 items-center">
          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            className="hidden"
            onChange={handleFilePick}
          />
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={() => { playSound("click"); fileRef.current?.click(); }}
            disabled={isLoading}
            className="text-[#00C853] hover:bg-[#00C853]/10 shrink-0"
            title="העלה תמונה"
          >
            🖼️
          </Button>
          <Input
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={pendingImage ? "שאל על התמונה..." : "כתוב הודעה או 'צייר לי...'"}
            className="flex-1 border-[#00C853]/30 focus:border-[#00C853]"
            onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }}
            disabled={isLoading}
          />
          <Button onClick={send} disabled={isLoading || (!input.trim() && !pendingImage)} className="bg-[#00C853] hover:bg-[#00C853]/90 text-white px-6">
            שלח
          </Button>
        </div>
      </Card>

      {messages.length > 0 && (
        <div className="text-center">
          <Button variant="ghost" size="sm" onClick={clearChat} className="text-xs text-muted-foreground hover:text-destructive">
            🗑️ נקה שיחה
          </Button>
        </div>
      )}
    </div>
  );
};
