// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { z } from "npm:zod@^4.4.3";
var list_posts_default = defineTool({
  name: "list_posts",
  title: "List marketplace posts",
  description: "List the most recent Schooltrade marketplace posts (ads for items being sold or auctioned).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("How many posts to return (max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("posts").select("id, owner_name, description, price, current_bid_price, auction_active, posting_mode, created_at, photo_url").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data }
    };
  }
});

// src/lib/mcp/tools/search-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { z as z2 } from "npm:zod@^4.4.3";
var search_posts_default = defineTool2({
  name: "search_posts",
  title: "Search marketplace posts",
  description: "Search Schooltrade marketplace posts by keyword in description or seller name.",
  inputSchema: {
    query: z2.string().min(1).describe("Keyword to search for (Hebrew or English)."),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const like = `%${query}%`;
    const { data, error } = await supabase.from("posts").select("id, owner_name, description, price, current_bid_price, auction_active, created_at, photo_url").or(`description.ilike.${like},owner_name.ilike.${like}`).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data, query }
    };
  }
});

// src/lib/mcp/tools/list-school-news.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_school_news_default = defineTool3({
  name: "list_school_news",
  title: "List school news",
  description: "Return the latest school news published on Schooltrade.",
  inputSchema: {
    limit: z3.number().int().min(1).max(30).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("school_news").select("id, author_name, title, content, is_official, created_at").eq("is_public", true).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { news: data }
    };
  }
});

// src/lib/mcp/tools/list-books.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.76.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_books_default = defineTool4({
  name: "list_books",
  title: "List books",
  description: "List books available in the Schooltrade library.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("books").select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { books: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "schooltrade-mcp",
  title: "Schooltrade",
  version: "0.1.0",
  instructions: "Tools for the Schooltrade school marketplace. Use `list_posts` or `search_posts` to browse ads for items being sold or auctioned, `list_school_news` for the latest school announcements, and `list_books` for the library. All content is in Hebrew.",
  tools: [list_posts_default, search_posts_default, list_school_news_default, list_books_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
